import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Unique Auditing",
	description: "Generated by create next app",
};
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "./context/AuthProvider";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<Navbar />
					{children}
					<Footer />
					<ToastContainer />
				</AuthProvider>
			</body>
		</html>
	);
}
