import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import GlassProvider from "glass-js";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Unique Auditing",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<GlassProvider>
					<Navbar />
					{children}
					<Footer />
				</GlassProvider>
			</body>
		</html>
	);
}
